"""initial schema

Revision ID: 7fb25ebbd4f5
Revises: 
Create Date: 2026-09-05 18:16:01.523512

"""
from alembic import op
import sqlalchemy as sa


revision = '7fb25ebbd4f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('standard', 'knockout', 'championship', 'endless', name='tournamenttype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('scoring_rules', sa.JSON(), nullable=True),
    sa.Column('skip_flag_symbol', sa.String(length=8), nullable=False),
    sa.Column('bracket_size', sa.Integer(), nullable=True),
    sa.Column('rounds_per_match', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'tiebreak', 'playoff', 'finished', name='tournamentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=64), nullable=False),
    sa.Column('admin_note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_access_token'), 'users', ['access_token'], unique=True)
    op.create_table('daily_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=16), nullable=False),
    sa.Column('calendar_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('suggested', 'confirmed', name='dailywordstatus'), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'day_number', name='uq_word_per_day')
    )
    op.create_table('tournament_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('callsign', sa.String(length=100), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('joined_on_day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('daily_word_id', sa.Integer(), nullable=False),
    sa.Column('guesses', sa.JSON(), nullable=False),
    sa.Column('attempts_used', sa.Integer(), nullable=False),
    sa.Column('solved', sa.Boolean(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('admin_note', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['daily_word_id'], ['daily_words.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['tournament_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'daily_word_id', name='uq_attempt_per_day')
    )
    op.create_table('playoff_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('entry_a_id', sa.Integer(), nullable=True),
    sa.Column('entry_b_id', sa.Integer(), nullable=True),
    sa.Column('winner_entry_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'finished', name='playoffmatchstatus'), nullable=False),
    sa.Column('next_match_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('admin_note', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['entry_a_id'], ['tournament_entries.id'], ),
    sa.ForeignKeyConstraint(['entry_b_id'], ['tournament_entries.id'], ),
    sa.ForeignKeyConstraint(['next_match_id'], ['playoff_matches.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['winner_entry_id'], ['tournament_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tiebreak_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('daily_word_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('previous_round_id', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('manual_order', sa.JSON(), nullable=True),
    sa.Column('admin_note', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['daily_word_id'], ['daily_words.id'], ),
    sa.ForeignKeyConstraint(['previous_round_id'], ['tiebreak_rounds.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playoff_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('game_number', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=16), nullable=False),
    sa.Column('calendar_date', sa.Date(), nullable=False),
    sa.Column('is_sudden_death', sa.Boolean(), nullable=False),
    sa.Column('entry_a_guesses', sa.JSON(), nullable=False),
    sa.Column('entry_a_attempts_used', sa.Integer(), nullable=True),
    sa.Column('entry_a_solved', sa.Boolean(), nullable=True),
    sa.Column('entry_a_technical_loss', sa.Boolean(), nullable=False),
    sa.Column('entry_b_guesses', sa.JSON(), nullable=False),
    sa.Column('entry_b_attempts_used', sa.Integer(), nullable=True),
    sa.Column('entry_b_solved', sa.Boolean(), nullable=True),
    sa.Column('entry_b_technical_loss', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['playoff_matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'game_number', name='uq_game_per_match')
    )
    op.create_table('tiebreak_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['tournament_entries.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['tiebreak_rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'entry_id', name='uq_tiebreak_participant')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tiebreak_participants')
    op.drop_table('playoff_games')
    op.drop_table('tiebreak_rounds')
    op.drop_table('playoff_matches')
    op.drop_table('attempts')
    op.drop_table('tournament_entries')
    op.drop_table('daily_words')
    op.drop_index(op.f('ix_users_access_token'), table_name='users')
    op.drop_table('users')
    op.drop_table('tournaments')
    # ### end Alembic commands ###
